version: 2
jobs:
  build:
    docker:
      - image: python:3

    environment:
      SECRET_KEY: DEV

    steps:
      - checkout
      - run: pip install pytest coverage
      - run: pip install -e .
      - run: coverage run -m pytest
      - run: coverage report
